{"plaka":1,"il":"Adana"}
{"plaka":2,"il":"Adıyaman"}
{"plaka":3,"il":"Afyon"}
{"plaka":4,"il":"Ağrı"}
{"plaka":5,"il":"Amasya"}
{"plaka":6,"il":"Ankara"}
{"plaka":7,"il":"Antalya"}
{"plaka":8,"il":"Artvin"}
{"plaka":9,"il":"Aydın"}
{"plaka":10,"il":"Balıkesir"}
{"plaka":11,"il":"Bilecik"}
{"plaka":12,"il":"Bingöl"}
{"plaka":13,"il":"Bitlis"}
{"plaka":14,"il":"Bolu"}
{"plaka":15,"il":"Burdur"}
{"plaka":16,"il":"Bursa"}
{"plaka":17,"il":"Çanakkale"}
{"plaka":18,"il":"Çankırı"}
{"plaka":19,"il":"Çorum"}
{"plaka":20,"il":"Denizli"}
{"plaka":21,"il":"Diyarbakır"}
{"plaka":22,"il":"Edirne"}
{"plaka":23,"il":"Elazığ"}
{"plaka":24,"il":"Erzincan"}
{"plaka":25,"il":"Erzurum"}
{"plaka":26,"il":"Eskişehir"}
{"plaka":27,"il":"Gaziantep"}
{"plaka":28,"il":"Giresun"}
{"plaka":29,"il":"Gümüşhane"}
{"plaka":30,"il":"Hakkari"}
{"plaka":31,"il":"Hatay"}
{"plaka":32,"il":"Isparta"}
{"plaka":33,"il":"Mersin"}
{"plaka":34,"il":"İstanbul"}
{"plaka":35,"il":"İzmir"}
{"plaka":36,"il":"Kars"}
{"plaka":37,"il":"Kastamonu"}
{"plaka":38,"il":"Kayseri"}
{"plaka":39,"il":"Kırklareli"}
{"plaka":40,"il":"Kırşehir"}
{"plaka":41,"il":"Kocaeli"}
{"plaka":42,"il":"Konya"}
{"plaka":43,"il":"Kütahya"}
{"plaka":44,"il":"Malatya"}
{"plaka":45,"il":"Manisa"}
{"plaka":46,"il":"Kahramanmaraş"}
{"plaka":47,"il":"Mardin"}
{"plaka":48,"il":"Muğla"}
{"plaka":49,"il":"Muş"}
{"plaka":50,"il":"Nevşehir"}
{"plaka":51,"il":"Niğde"}
{"plaka":52,"il":"Ordu"}
{"plaka":53,"il":"Rize"}
{"plaka":54,"il":"Sakarya"}
{"plaka":55,"il":"Samsun"}
{"plaka":56,"il":"Siirt"}
{"plaka":57,"il":"Sinop"}
{"plaka":58,"il":"Sivas"}
{"plaka":59,"il":"Tekirdağ"}
{"plaka":60,"il":"Tokat"}
{"plaka":61,"il":"Trabzon"}
{"plaka":62,"il":"Tunceli"}
{"plaka":63,"il":"Şanlıurfa"}
{"plaka":64,"il":"Uşak"}
{"plaka":65,"il":"Van"}
{"plaka":66,"il":"Yozgat"}
{"plaka":67,"il":"Zonguldak"}
{"plaka":68,"il":"Aksaray"}
{"plaka":69,"il":"Bayburt"}
{"plaka":70,"il":"Karaman"}
{"plaka":71,"il":"Kırıkkale"}
{"plaka":72,"il":"Batman"}
{"plaka":73,"il":"Şırnak"}
{"plaka":74,"il":"Bartın"}
{"plaka":75,"il":"Ardahan"}
{"plaka":76,"il":"Iğdır"}
{"plaka":77,"il":"Yalova"}
{"plaka":78,"il":"Karabük"}
{"plaka":79,"il":"Kilis"}
{"plaka":80,"il":"Osmaniye"}
{"plaka":81,"il":"Düzce"}
